//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Buffers;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace TestML;

/// <summary>
/// Language-agnostic Test-Spec – version 1.6
/// </summary>
public readonly partial struct WorkingDraft
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct TestCase
    {
        /// <summary>
        /// Generated from JSON Schema.
        /// </summary>
        public readonly partial struct RequiredExpr
        {
            /// <summary>
            /// Generated from JSON Schema.
            /// </summary>
            [System.Text.Json.Serialization.JsonConverter(typeof(Corvus.Json.Internal.JsonValueConverter<TimeoutEntity>))]
            public readonly partial struct TimeoutEntity
                : IJsonValue<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity>
            {
                private readonly Backing backing;
                private readonly JsonElement jsonElementBacking;
                private readonly string stringBacking;
                private readonly BinaryJsonNumber numberBacking;

                /// <summary>
                /// Initializes a new instance of the <see cref="TimeoutEntity"/> struct.
                /// </summary>
                public TimeoutEntity()
                {
                    this.jsonElementBacking = default;
                    this.backing = Backing.JsonElement;
                    this.stringBacking = string.Empty;
                    this.numberBacking = default;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="TimeoutEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public TimeoutEntity(in JsonElement value)
                {
                    this.jsonElementBacking = value;
                    this.backing = Backing.JsonElement;
                    this.stringBacking = string.Empty;
                    this.numberBacking = default;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="TimeoutEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public TimeoutEntity(BinaryJsonNumber value)
                {
                    this.backing = Backing.Number;
                    this.jsonElementBacking = default;
                    this.stringBacking = string.Empty;
                    this.numberBacking = value;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="TimeoutEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public TimeoutEntity(string value)
                {
                    this.backing = Backing.String;
                    this.jsonElementBacking = default;
                    this.stringBacking = value;
                    this.numberBacking = default;
                }

                /// <summary>
                /// Gets the schema location from which this type was generated.
                /// </summary>
                public static string SchemaLocation { get; } = "https://endjin.com/workspaces/test-ml/docs/spec/draft/working-draft.json#/definitions/testCase/properties/act/properties/timeout";

                /// <summary>
                /// Gets a Null instance.
                /// </summary>
                public static TimeoutEntity Null { get; } = new(JsonValueHelpers.NullElement);

                /// <summary>
                /// Gets an Undefined instance.
                /// </summary>
                public static TimeoutEntity Undefined { get; }

                /// <summary>
                /// Gets the default instance.
                /// </summary>
                public static TimeoutEntity DefaultInstance { get; }

                /// <inheritdoc/>
                public JsonAny AsAny
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.String) != 0)
                        {
                            return new(this.stringBacking);
                        }

                        if ((this.backing & Backing.Number) != 0)
                        {
                            return new(this.numberBacking);
                        }

                        if ((this.backing & Backing.Null) != 0)
                        {
                            return JsonAny.Null;
                        }

                        return JsonAny.Undefined;
                    }
                }

                /// <inheritdoc/>
                public JsonElement AsJsonElement
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return this.jsonElementBacking;
                        }

                        if ((this.backing & Backing.String) != 0)
                        {
                            return JsonValueHelpers.StringToJsonElement(this.stringBacking);
                        }

                        if ((this.backing & Backing.Number) != 0)
                        {
                            return JsonValueHelpers.NumberToJsonElement(this.numberBacking);
                        }

                        if ((this.backing & Backing.Null) != 0)
                        {
                            return JsonValueHelpers.NullElement;
                        }

                        return default;
                    }
                }

                /// <inheritdoc/>
                public JsonString AsString
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.String) != 0)
                        {
                            return new(this.stringBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                JsonBoolean IJsonValue.AsBoolean
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                public JsonNumber AsNumber
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.Number) != 0)
                        {
                            return new(this.numberBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                JsonObject IJsonValue.AsObject
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                JsonArray IJsonValue.AsArray
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <summary>
                /// Gets the instance as a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity" />.
                /// </summary>
                public TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity AsOneOf0Entity
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>();
                    }
                }

                /// <summary>
                /// Gets a value indicating whether the instance is a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity" />.
                /// </summary>
                public bool IsOneOf0Entity
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>().IsValid();
                    }
                }

                /// <summary>
                /// Gets the instance as a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity" />.
                /// </summary>
                public TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity AsOneOf1Entity
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>();
                    }
                }

                /// <summary>
                /// Gets a value indicating whether the instance is a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity" />.
                /// </summary>
                public bool IsOneOf1Entity
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>().IsValid();
                    }
                }

                /// <inheritdoc/>
                public bool HasJsonElementBacking
                {
                    get
                    {
                        return (this.backing & Backing.JsonElement) != 0;
                    }
                }

                /// <inheritdoc/>
                public bool HasDotnetBacking
                {
                    get
                    {
                        return (this.backing & Backing.Dotnet) != 0;
                    }
                }

                /// <inheritdoc/>
                public JsonValueKind ValueKind
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return this.jsonElementBacking.ValueKind;
                        }

                        if ((this.backing & Backing.String) != 0)
                        {
                            return JsonValueKind.String;
                        }

                        if ((this.backing & Backing.Number) != 0)
                        {
                            return JsonValueKind.Number;
                        }

                        return JsonValueKind.Undefined;
                    }
                }

                /// <summary>
                /// Conversion from JsonAny.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator TimeoutEntity(JsonAny value)
                {
                    return value.As<TimeoutEntity>();
                }

                /// <summary>
                /// Conversion to JsonAny.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator JsonAny(TimeoutEntity value)
                {
                    return value.AsAny;
                }

                /// <summary>
                /// Conversion to <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static explicit operator TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity(TimeoutEntity value)
                {
                    return value.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>();
                }

                /// <summary>
                /// Conversion from <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator TimeoutEntity(TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity value)
                {
                    return value.As<TimeoutEntity>();
                }

                /// <summary>
                /// Conversion to <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static explicit operator TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity(TimeoutEntity value)
                {
                    return value.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>();
                }

                /// <summary>
                /// Conversion from <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator TimeoutEntity(TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity value)
                {
                    return value.As<TimeoutEntity>();
                }

                /// <summary>
                /// Operator ==.
                /// </summary>
                /// <param name="left">The lhs of the operator.</param>
                /// <param name="right">The rhs of the operator.</param>
                /// <returns>
                /// <c>True</c> if the values are equal.
                /// </returns>
                public static bool operator ==(in TimeoutEntity left, in TimeoutEntity right)
                {
                    return left.Equals(right);
                }

                /// <summary>
                /// Operator !=.
                /// </summary>
                /// <param name="left">The lhs of the operator.</param>
                /// <param name="right">The rhs of the operator.</param>
                /// <returns>
                /// <c>True</c> if the values are not equal.
                /// </returns>
                public static bool operator !=(in TimeoutEntity left, in TimeoutEntity right)
                {
                    return !left.Equals(right);
                }

                /// <summary>
                /// Gets an instance of the JSON value from a <see cref="JsonElement"/> value.
                /// </summary>
                /// <param name="value">The <see cref="JsonElement"/> value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the <see cref="JsonElement"/>.</returns>
                /// <remarks>The returned value will have a <see cref = "IJsonValue.ValueKind"/> of <see cref = "JsonValueKind.Undefined"/> if the
                /// value cannot be constructed from the given instance (e.g. because they have an incompatible .NET backing type).
                /// </remarks>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static TimeoutEntity FromJson(in JsonElement value)
                {
                    return new(value);
                }

                /// <summary>
                /// Gets an instance of the JSON value from a <see cref="JsonAny"/> value.
                /// </summary>
                /// <param name="value">The <see cref="JsonAny"/> value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the <see cref="JsonAny"/> value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static TimeoutEntity FromAny(in JsonAny value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.String => new(value.AsString.GetString()!),
                        JsonValueKind.Number => new(value.AsNumber.AsBinaryJsonNumber),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static TimeoutEntity IJsonValue<TimeoutEntity>.FromBoolean<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static TimeoutEntity FromString<TValue>(in TValue value)
                    where TValue : struct, IJsonString<TValue>
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.String => new(value.GetString()!),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static TimeoutEntity FromNumber<TValue>(in TValue value)
                    where TValue : struct, IJsonNumber<TValue>
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.Number => new(value.AsBinaryJsonNumber),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static TimeoutEntity IJsonValue<TimeoutEntity>.FromObject<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static TimeoutEntity IJsonValue<TimeoutEntity>.FromArray<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static TimeoutEntity Parse(string source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static TimeoutEntity Parse(Stream source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static TimeoutEntity Parse(ReadOnlyMemory<byte> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static TimeoutEntity Parse(ReadOnlyMemory<char> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static TimeoutEntity Parse(ReadOnlySequence<byte> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static TimeoutEntity ParseValue(string source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<TimeoutEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<TimeoutEntity>(source.AsSpan());
#endif
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static TimeoutEntity ParseValue(ReadOnlySpan<char> source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<TimeoutEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<TimeoutEntity>(source);
#endif
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static TimeoutEntity ParseValue(ReadOnlySpan<byte> source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<TimeoutEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<TimeoutEntity>(source);
#endif
                }

                /// <summary>
                /// Parses the TimeoutEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static TimeoutEntity ParseValue(ref Utf8JsonReader source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<TimeoutEntity>.ParseValue(ref source);
#else
                    return JsonValueHelpers.ParseValue<TimeoutEntity>(ref source);
#endif
                }

                /// <summary>
                /// Gets the value as an instance of the target value.
                /// </summary>
                /// <typeparam name="TTarget">The type of the target.</typeparam>
                /// <returns>An instance of the target type.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public TTarget As<TTarget>()
                    where TTarget : struct, IJsonValue<TTarget>
                {
#if NET8_0_OR_GREATER
                    if ((this.backing & Backing.JsonElement) != 0)
                    {
                        return TTarget.FromJson(this.jsonElementBacking);
                    }

                    if ((this.backing & Backing.String) != 0)
                    {
                        return TTarget.FromString(this.AsString);
                    }

                    if ((this.backing & Backing.Number) != 0)
                    {
                        return TTarget.FromNumber(this.AsNumber);
                    }

                    if ((this.backing & Backing.Null) != 0)
                    {
                        return TTarget.Null;
                    }

                    return TTarget.Undefined;
#else
                    return this.As<TimeoutEntity, TTarget>();
#endif
                }

                /// <inheritdoc/>
                public override bool Equals(object? obj)
                {
                    return
                        (obj is IJsonValue jv && this.Equals(jv.As<TimeoutEntity>())) ||
                        (obj is null && this.IsNull());
                }

                /// <inheritdoc/>
                public bool Equals<T>(in T other)
                    where T : struct, IJsonValue<T>
                {
                    return this.Equals(other.As<TimeoutEntity>());
                }

                /// <summary>
                /// Equality comparison.
                /// </summary>
                /// <param name="other">The other item with which to compare.</param>
                /// <returns><see langword="true"/> if the values were equal.</returns>
                public bool Equals(in TimeoutEntity other)
                {
                    JsonValueKind thisKind = this.ValueKind;
                    JsonValueKind otherKind = other.ValueKind;
                    if (thisKind != otherKind)
                    {
                        return false;
                    }

                    if (thisKind == JsonValueKind.Null || thisKind == JsonValueKind.Undefined)
                    {
                        return true;
                    }

                    if (thisKind == JsonValueKind.Number)
                    {
                        if (this.backing == Backing.Number && other.backing == Backing.Number)
                        {
                            return BinaryJsonNumber.Equals(this.numberBacking, other.numberBacking);
                        }

                        if (this.backing == Backing.Number && other.backing == Backing.JsonElement)
                        {
                            return BinaryJsonNumber.Equals(this.numberBacking, other.jsonElementBacking);
                        }

                        if (this.backing == Backing.JsonElement && other.backing == Backing.Number)
                        {
                            return BinaryJsonNumber.Equals(this.jsonElementBacking, other.numberBacking);
                        }

                        if (this.jsonElementBacking.TryGetDouble(out double lDouble))
                        {
                            if (other.jsonElementBacking.TryGetDouble(out double rDouble))
                            {
                                return lDouble.Equals(rDouble);
                            }
                        }

                        if (this.jsonElementBacking.TryGetDecimal(out decimal lDecimal))
                        {
                            if (other.jsonElementBacking.TryGetDecimal(out decimal rDecimal))
                            {
                                return lDecimal.Equals(rDecimal);
                            }
                        }
                    }

                    if (thisKind == JsonValueKind.String)
                    {
                        if (this.backing == Backing.JsonElement)
                        {
                            if (other.backing == Backing.String)
                            {
                                return this.jsonElementBacking.ValueEquals(other.stringBacking);
                            }
                            else
                            {
                                other.jsonElementBacking.TryGetValue(CompareValues, this.jsonElementBacking, out bool areEqual);
                                return areEqual;
                            }

                        }

                        if (other.backing == Backing.JsonElement)
                        {
                            return other.jsonElementBacking.ValueEquals(this.stringBacking);
                        }

                        return this.stringBacking.Equals(other.stringBacking);

                        static bool CompareValues(ReadOnlySpan<byte> span, in JsonElement firstItem, out bool value)
                        {
                            value = firstItem.ValueEquals(span);
                            return true;
                        }
                    }

                    return false;
                }

                /// <inheritdoc/>
                public void WriteTo(Utf8JsonWriter writer)
                {
                    if ((this.backing & Backing.JsonElement) != 0)
                    {
                        if (this.jsonElementBacking.ValueKind != JsonValueKind.Undefined)
                        {
                            this.jsonElementBacking.WriteTo(writer);
                        }

                        return;
                    }

                    if ((this.backing & Backing.Number) != 0)
                    {
                        this.numberBacking.WriteTo(writer);

                        return;
                    }

                    if ((this.backing & Backing.String) != 0)
                    {
                        writer.WriteStringValue(this.stringBacking);

                        return;
                    }

                    if ((this.backing & Backing.Null) != 0)
                    {
                        writer.WriteNullValue();

                        return;
                    }
                }

                /// <inheritdoc/>
                public override int GetHashCode()
                {
                    return this.ValueKind switch
                    {
                        JsonValueKind.Array => JsonValueHelpers.GetArrayHashCode(((IJsonValue)this).AsArray),
                        JsonValueKind.Object => JsonValueHelpers.GetObjectHashCode(((IJsonValue)this).AsObject),
                        JsonValueKind.Number => JsonValueHelpers.GetHashCodeForNumber(this),
                        JsonValueKind.String => JsonValueHelpers.GetHashCodeForString(this),
                        JsonValueKind.True => true.GetHashCode(),
                        JsonValueKind.False => false.GetHashCode(),
                        JsonValueKind.Null => JsonValueHelpers.NullHashCode,
                        _ => JsonValueHelpers.UndefinedHashCode,
                    };
                }

                /// <inheritdoc/>
                public override string ToString()
                {
                    return this.Serialize();
                }

                /// <summary>
                /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
                /// </summary>
                /// <typeparam name="TIn">The immutable context to pass in to the match function.</typeparam>
                /// <typeparam name="TOut">The result of calling the match function.</typeparam>
                /// <param name="context">The context to pass to the match function.</param>
                /// <param name="matchOneOf0Entity">Match a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity"/>.</param>
                /// <param name="matchOneOf1Entity">Match a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity"/>.</param>
                /// <param name="defaultMatch">Match any other value.</param>
                /// <returns>An instance of the value returned by the match function.</returns>
                public TOut Match<TIn, TOut>(
                    in TIn context,
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity, TIn, TOut> matchOneOf0Entity,
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity, TIn, TOut> matchOneOf1Entity,
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity, TIn, TOut> defaultMatch)
                {
                    TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity matchOneOf0EntityValue = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>();
                    if (matchOneOf0EntityValue.IsValid())
                    {
                        return matchOneOf0Entity(matchOneOf0EntityValue, context);
                    }

                    TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity matchOneOf1EntityValue = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>();
                    if (matchOneOf1EntityValue.IsValid())
                    {
                        return matchOneOf1Entity(matchOneOf1EntityValue, context);
                    }

                    return defaultMatch(this, context);
                }

                /// <summary>
                /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
                /// </summary>
                /// <typeparam name="TOut">The result of calling the match function.</typeparam>
                /// <param name="matchOneOf0Entity">Match a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity"/>.</param>
                /// <param name="matchOneOf1Entity">Match a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity"/>.</param>
                /// <param name="defaultMatch">Match any other value.</param>
                /// <returns>An instance of the value returned by the match function.</returns>
                public TOut Match<TOut>(
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity, TOut> matchOneOf0Entity,
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity, TOut> matchOneOf1Entity,
                    Matcher<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity, TOut> defaultMatch)
                {
                    TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity matchOneOf0EntityValue = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>();
                    if (matchOneOf0EntityValue.IsValid())
                    {
                        return matchOneOf0Entity(matchOneOf0EntityValue);
                    }

                    TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity matchOneOf1EntityValue = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>();
                    if (matchOneOf1EntityValue.IsValid())
                    {
                        return matchOneOf1Entity(matchOneOf1EntityValue);
                    }

                    return defaultMatch(this);
                }

                /// <summary>
                /// Gets the value as a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity" />.
                /// </summary>
                /// <param name="result">The result of the conversions.</param>
                /// <returns><see langword="true" /> if the conversion was valid.</returns>
                public bool TryGetAsOneOf0Entity(out TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity result)
                {
                    result = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf0Entity>();
                    return result.IsValid();
                }

                /// <summary>
                /// Gets the value as a <see cref="TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity" />.
                /// </summary>
                /// <param name="result">The result of the conversions.</param>
                /// <returns><see langword="true" /> if the conversion was valid.</returns>
                public bool TryGetAsOneOf1Entity(out TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity result)
                {
                    result = this.As<TestML.WorkingDraft.TestCase.RequiredExpr.TimeoutEntity.OneOf1Entity>();
                    return result.IsValid();
                }
            }
        }
    }
}
