//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Buffers;
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace TestML;

/// <summary>
/// Language-agnostic Test-Spec – version 1.6
/// </summary>
public readonly partial struct WorkingDraft
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct TestCase
    {
        /// <summary>
        /// Generated from JSON Schema.
        /// </summary>
        public readonly partial struct ArrangeEntity
        {
            /// <summary>
            /// Generated from JSON Schema.
            /// </summary>
            [System.Text.Json.Serialization.JsonConverter(typeof(Corvus.Json.Internal.JsonValueConverter<VarsEntity>))]
            public readonly partial struct VarsEntity
                : IJsonValue<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity>
            {
                private readonly Backing backing;
                private readonly JsonElement jsonElementBacking;
                private readonly ImmutableList<JsonAny> arrayBacking;
                private readonly ImmutableList<JsonObjectProperty> objectBacking;

                /// <summary>
                /// Initializes a new instance of the <see cref="VarsEntity"/> struct.
                /// </summary>
                public VarsEntity()
                {
                    this.jsonElementBacking = default;
                    this.backing = Backing.JsonElement;
                    this.arrayBacking = ImmutableList<JsonAny>.Empty;
                    this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="VarsEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public VarsEntity(in JsonElement value)
                {
                    this.jsonElementBacking = value;
                    this.backing = Backing.JsonElement;
                    this.arrayBacking = ImmutableList<JsonAny>.Empty;
                    this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="VarsEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public VarsEntity(ImmutableList<JsonAny> value)
                {
                    this.backing = Backing.Array;
                    this.jsonElementBacking = default;
                    this.arrayBacking = value;
                    this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="VarsEntity"/> struct.
                /// </summary>
                /// <param name="value">The value from which to construct the instance.</param>
                public VarsEntity(ImmutableList<JsonObjectProperty> value)
                {
                    this.backing = Backing.Object;
                    this.jsonElementBacking = default;
                    this.arrayBacking = ImmutableList<JsonAny>.Empty;
                    this.objectBacking = value;
                }

                /// <summary>
                /// Gets the schema location from which this type was generated.
                /// </summary>
                public static string SchemaLocation { get; } = "https://endjin.com/workspaces/test-ml/docs/spec/draft/working-draft.json#/definitions/testCase/properties/arrange/properties/vars";

                /// <summary>
                /// Gets a Null instance.
                /// </summary>
                public static VarsEntity Null { get; } = new(JsonValueHelpers.NullElement);

                /// <summary>
                /// Gets an Undefined instance.
                /// </summary>
                public static VarsEntity Undefined { get; }

                /// <summary>
                /// Gets the default instance.
                /// </summary>
                public static VarsEntity DefaultInstance { get; }

                /// <inheritdoc/>
                public JsonAny AsAny
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.Array) != 0)
                        {
                            return new(this.arrayBacking);
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            return new(this.objectBacking);
                        }

                        if ((this.backing & Backing.Null) != 0)
                        {
                            return JsonAny.Null;
                        }

                        return JsonAny.Undefined;
                    }
                }

                /// <inheritdoc/>
                public JsonElement AsJsonElement
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return this.jsonElementBacking;
                        }

                        if ((this.backing & Backing.Array) != 0)
                        {
                            return JsonValueHelpers.ArrayToJsonElement(this.arrayBacking);
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            return JsonValueHelpers.ObjectToJsonElement(this.objectBacking);
                        }

                        if ((this.backing & Backing.Null) != 0)
                        {
                            return JsonValueHelpers.NullElement;
                        }

                        return default;
                    }
                }

                /// <inheritdoc/>
                JsonString IJsonValue.AsString
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                JsonBoolean IJsonValue.AsBoolean
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                JsonNumber IJsonValue.AsNumber
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                public JsonObject AsObject
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            return new(this.objectBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <inheritdoc/>
                public JsonArray AsArray
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return new(this.jsonElementBacking);
                        }

                        if ((this.backing & Backing.Array) != 0)
                        {
                            return new(this.arrayBacking);
                        }

                        throw new InvalidOperationException();
                    }
                }

                /// <summary>
                /// Gets the instance as a <see cref="Corvus.Json.JsonObject" />.
                /// </summary>
                public Corvus.Json.JsonObject AsJsonObject
                {
                    get
                    {
                        return this.As<Corvus.Json.JsonObject>();
                    }
                }

                /// <summary>
                /// Gets a value indicating whether the instance is a <see cref="Corvus.Json.JsonObject" />.
                /// </summary>
                public bool IsJsonObject
                {
                    get
                    {
                        return this.As<Corvus.Json.JsonObject>().IsValid();
                    }
                }

                /// <summary>
                /// Gets the instance as a <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray" />.
                /// </summary>
                public TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray AsJsonObjectArray
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>();
                    }
                }

                /// <summary>
                /// Gets a value indicating whether the instance is a <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray" />.
                /// </summary>
                public bool IsJsonObjectArray
                {
                    get
                    {
                        return this.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>().IsValid();
                    }
                }

                /// <inheritdoc/>
                public bool HasJsonElementBacking
                {
                    get
                    {
                        return (this.backing & Backing.JsonElement) != 0;
                    }
                }

                /// <inheritdoc/>
                public bool HasDotnetBacking
                {
                    get
                    {
                        return (this.backing & Backing.Dotnet) != 0;
                    }
                }

                /// <inheritdoc/>
                public JsonValueKind ValueKind
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            return this.jsonElementBacking.ValueKind;
                        }

                        if ((this.backing & Backing.Array) != 0)
                        {
                            return JsonValueKind.Array;
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            return JsonValueKind.Object;
                        }

                        return JsonValueKind.Undefined;
                    }
                }

                /// <summary>
                /// Conversion from JsonAny.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator VarsEntity(JsonAny value)
                {
                    return value.As<VarsEntity>();
                }

                /// <summary>
                /// Conversion to JsonAny.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator JsonAny(VarsEntity value)
                {
                    return value.AsAny;
                }

                /// <summary>
                /// Conversion to <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static explicit operator TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray(VarsEntity value)
                {
                    return value.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>();
                }

                /// <summary>
                /// Conversion from <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray"/>.
                /// </summary>
                /// <param name="value">The value from which to convert.</param>
                public static implicit operator VarsEntity(TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray value)
                {
                    return value.As<VarsEntity>();
                }

                /// <summary>
                /// Operator ==.
                /// </summary>
                /// <param name="left">The lhs of the operator.</param>
                /// <param name="right">The rhs of the operator.</param>
                /// <returns>
                /// <c>True</c> if the values are equal.
                /// </returns>
                public static bool operator ==(in VarsEntity left, in VarsEntity right)
                {
                    return left.Equals(right);
                }

                /// <summary>
                /// Operator !=.
                /// </summary>
                /// <param name="left">The lhs of the operator.</param>
                /// <param name="right">The rhs of the operator.</param>
                /// <returns>
                /// <c>True</c> if the values are not equal.
                /// </returns>
                public static bool operator !=(in VarsEntity left, in VarsEntity right)
                {
                    return !left.Equals(right);
                }

                /// <summary>
                /// Gets an instance of the JSON value from a <see cref="JsonElement"/> value.
                /// </summary>
                /// <param name="value">The <see cref="JsonElement"/> value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the <see cref="JsonElement"/>.</returns>
                /// <remarks>The returned value will have a <see cref = "IJsonValue.ValueKind"/> of <see cref = "JsonValueKind.Undefined"/> if the
                /// value cannot be constructed from the given instance (e.g. because they have an incompatible .NET backing type).
                /// </remarks>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static VarsEntity FromJson(in JsonElement value)
                {
                    return new(value);
                }

                /// <summary>
                /// Gets an instance of the JSON value from a <see cref="JsonAny"/> value.
                /// </summary>
                /// <param name="value">The <see cref="JsonAny"/> value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the <see cref="JsonAny"/> value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static VarsEntity FromAny(in JsonAny value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.Array => new(value.AsArray.AsImmutableList()),
                        JsonValueKind.Object => new(value.AsObject.AsPropertyBacking()),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static VarsEntity IJsonValue<VarsEntity>.FromBoolean<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static VarsEntity IJsonValue<VarsEntity>.FromString<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

#if NET8_0_OR_GREATER
                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                static VarsEntity IJsonValue<VarsEntity>.FromNumber<TValue>(in TValue value)
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return Undefined;
                }
#endif

                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static VarsEntity FromObject<TValue>(in TValue value)
                    where TValue : struct, IJsonObject<TValue>
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.Object => new(value.AsPropertyBacking()),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

                /// <summary>
                /// Gets an instance of the JSON value from the provided value.
                /// </summary>
                /// <typeparam name="TValue">The type of the value.</typeparam>
                /// <param name="value">The value from which to instantiate the instance.</param>
                /// <returns>An instance of this type, initialized from the provided value.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static VarsEntity FromArray<TValue>(in TValue value)
                    where TValue : struct, IJsonArray<TValue>
                {
                    if (value.HasJsonElementBacking)
                    {
                        return new(value.AsJsonElement);
                    }

                    return value.ValueKind switch
                    {
                        JsonValueKind.Array => new(value.AsImmutableList()),
                        JsonValueKind.Null => Null,
                        _ => Undefined,
                    };
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static VarsEntity Parse(string source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static VarsEntity Parse(Stream source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static VarsEntity Parse(ReadOnlyMemory<byte> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static VarsEntity Parse(ReadOnlyMemory<char> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                /// <param name="options">The (optional) JsonDocumentOptions.</param>
                public static VarsEntity Parse(ReadOnlySequence<byte> source, JsonDocumentOptions options = default)
                {
                    using var jsonDocument = JsonDocument.Parse(source, options);
                    return new(jsonDocument.RootElement.Clone());
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static VarsEntity ParseValue(string source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<VarsEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<VarsEntity>(source.AsSpan());
#endif
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static VarsEntity ParseValue(ReadOnlySpan<char> source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<VarsEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<VarsEntity>(source);
#endif
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static VarsEntity ParseValue(ReadOnlySpan<byte> source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<VarsEntity>.ParseValue(source);
#else
                    return JsonValueHelpers.ParseValue<VarsEntity>(source);
#endif
                }

                /// <summary>
                /// Parses the VarsEntity.
                /// </summary>
                /// <param name="source">The source of the JSON string to parse.</param>
                public static VarsEntity ParseValue(ref Utf8JsonReader source)
                {
#if NET8_0_OR_GREATER
                    return IJsonValue<VarsEntity>.ParseValue(ref source);
#else
                    return JsonValueHelpers.ParseValue<VarsEntity>(ref source);
#endif
                }

                /// <summary>
                /// Gets the value as an instance of the target value.
                /// </summary>
                /// <typeparam name="TTarget">The type of the target.</typeparam>
                /// <returns>An instance of the target type.</returns>
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public TTarget As<TTarget>()
                    where TTarget : struct, IJsonValue<TTarget>
                {
#if NET8_0_OR_GREATER
                    if ((this.backing & Backing.JsonElement) != 0)
                    {
                        return TTarget.FromJson(this.jsonElementBacking);
                    }

                    if ((this.backing & Backing.Array) != 0)
                    {
                        return TTarget.FromArray(this.AsArray);
                    }

                    if ((this.backing & Backing.Object) != 0)
                    {
                        return TTarget.FromObject(this.AsObject);
                    }

                    if ((this.backing & Backing.Null) != 0)
                    {
                        return TTarget.Null;
                    }

                    return TTarget.Undefined;
#else
                    return this.As<VarsEntity, TTarget>();
#endif
                }

                /// <inheritdoc/>
                public override bool Equals(object? obj)
                {
                    return
                        (obj is IJsonValue jv && this.Equals(jv.As<VarsEntity>())) ||
                        (obj is null && this.IsNull());
                }

                /// <inheritdoc/>
                public bool Equals<T>(in T other)
                    where T : struct, IJsonValue<T>
                {
                    return this.Equals(other.As<VarsEntity>());
                }

                /// <summary>
                /// Equality comparison.
                /// </summary>
                /// <param name="other">The other item with which to compare.</param>
                /// <returns><see langword="true"/> if the values were equal.</returns>
                public bool Equals(in VarsEntity other)
                {
                    JsonValueKind thisKind = this.ValueKind;
                    JsonValueKind otherKind = other.ValueKind;
                    if (thisKind != otherKind)
                    {
                        return false;
                    }

                    if (thisKind == JsonValueKind.Null || thisKind == JsonValueKind.Undefined)
                    {
                        return true;
                    }

                    if (thisKind == JsonValueKind.Array)
                    {
                        JsonArray thisArray = this.AsArray;
                        JsonArray otherArray = other.AsArray;
                        JsonArrayEnumerator lhs = thisArray.EnumerateArray();
                        JsonArrayEnumerator rhs = otherArray.EnumerateArray();
                        while (lhs.MoveNext())
                        {
                            if (!rhs.MoveNext())
                            {
                                return false;
                            }

                            if (!lhs.Current.Equals(rhs.Current))
                            {
                                return false;
                            }
                        }

                        return !rhs.MoveNext();
                    }

                    if (thisKind == JsonValueKind.Object)
                    {
                        JsonObject thisObject = this.AsObject;
                        JsonObject otherObject = other.AsObject;
                        int count = 0;
                        foreach (JsonObjectProperty property in thisObject.EnumerateObject())
                        {
                            if (!otherObject.TryGetProperty(property.Name, out JsonAny value) || !property.Value.Equals(value))
                            {
                                return false;
                            }

                            count++;
                        }

                        int otherCount = 0;
                        foreach (JsonObjectProperty otherProperty in otherObject.EnumerateObject())
                        {
                            otherCount++;
                            if (otherCount > count)
                            {
                                return false;
                            }
                        }

                        return count == otherCount;
                    }

                    return false;
                }

                /// <inheritdoc/>
                public void WriteTo(Utf8JsonWriter writer)
                {
                    if ((this.backing & Backing.JsonElement) != 0)
                    {
                        if (this.jsonElementBacking.ValueKind != JsonValueKind.Undefined)
                        {
                            this.jsonElementBacking.WriteTo(writer);
                        }

                        return;
                    }

                    if ((this.backing & Backing.Array) != 0)
                    {
                        JsonValueHelpers.WriteItems(this.arrayBacking, writer);

                        return;
                    }

                    if ((this.backing & Backing.Object) != 0)
                    {
                        JsonValueHelpers.WriteProperties(this.objectBacking, writer);

                        return;
                    }

                    if ((this.backing & Backing.Null) != 0)
                    {
                        writer.WriteNullValue();

                        return;
                    }
                }

                /// <inheritdoc/>
                public override int GetHashCode()
                {
                    return this.ValueKind switch
                    {
                        JsonValueKind.Array => JsonValueHelpers.GetArrayHashCode(this),
                        JsonValueKind.Object => JsonValueHelpers.GetObjectHashCode(this),
                        JsonValueKind.Number => JsonValueHelpers.GetHashCodeForNumber(((IJsonValue)this).AsNumber),
                        JsonValueKind.String => JsonValueHelpers.GetHashCodeForString(((IJsonValue)this).AsString),
                        JsonValueKind.True => true.GetHashCode(),
                        JsonValueKind.False => false.GetHashCode(),
                        JsonValueKind.Null => JsonValueHelpers.NullHashCode,
                        _ => JsonValueHelpers.UndefinedHashCode,
                    };
                }

                /// <inheritdoc/>
                public override string ToString()
                {
                    return this.Serialize();
                }

                /// <summary>
                /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
                /// </summary>
                /// <typeparam name="TIn">The immutable context to pass in to the match function.</typeparam>
                /// <typeparam name="TOut">The result of calling the match function.</typeparam>
                /// <param name="context">The context to pass to the match function.</param>
                /// <param name="matchJsonObject">Match a <see cref="Corvus.Json.JsonObject"/>.</param>
                /// <param name="matchJsonObjectArray">Match a <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray"/>.</param>
                /// <param name="defaultMatch">Match any other value.</param>
                /// <returns>An instance of the value returned by the match function.</returns>
                public TOut Match<TIn, TOut>(
                    in TIn context,
                    Matcher<Corvus.Json.JsonObject, TIn, TOut> matchJsonObject,
                    Matcher<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray, TIn, TOut> matchJsonObjectArray,
                    Matcher<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity, TIn, TOut> defaultMatch)
                {
                    Corvus.Json.JsonObject matchJsonObjectValue = this.As<Corvus.Json.JsonObject>();
                    if (matchJsonObjectValue.IsValid())
                    {
                        return matchJsonObject(matchJsonObjectValue, context);
                    }

                    TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray matchJsonObjectArrayValue = this.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>();
                    if (matchJsonObjectArrayValue.IsValid())
                    {
                        return matchJsonObjectArray(matchJsonObjectArrayValue, context);
                    }

                    return defaultMatch(this, context);
                }

                /// <summary>
                /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
                /// </summary>
                /// <typeparam name="TOut">The result of calling the match function.</typeparam>
                /// <param name="matchJsonObject">Match a <see cref="Corvus.Json.JsonObject"/>.</param>
                /// <param name="matchJsonObjectArray">Match a <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray"/>.</param>
                /// <param name="defaultMatch">Match any other value.</param>
                /// <returns>An instance of the value returned by the match function.</returns>
                public TOut Match<TOut>(
                    Matcher<Corvus.Json.JsonObject, TOut> matchJsonObject,
                    Matcher<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray, TOut> matchJsonObjectArray,
                    Matcher<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity, TOut> defaultMatch)
                {
                    Corvus.Json.JsonObject matchJsonObjectValue = this.As<Corvus.Json.JsonObject>();
                    if (matchJsonObjectValue.IsValid())
                    {
                        return matchJsonObject(matchJsonObjectValue);
                    }

                    TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray matchJsonObjectArrayValue = this.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>();
                    if (matchJsonObjectArrayValue.IsValid())
                    {
                        return matchJsonObjectArray(matchJsonObjectArrayValue);
                    }

                    return defaultMatch(this);
                }

                /// <summary>
                /// Gets the value as a <see cref="Corvus.Json.JsonObject" />.
                /// </summary>
                /// <param name="result">The result of the conversions.</param>
                /// <returns><see langword="true" /> if the conversion was valid.</returns>
                public bool TryGetAsJsonObject(out Corvus.Json.JsonObject result)
                {
                    result = this.As<Corvus.Json.JsonObject>();
                    return result.IsValid();
                }

                /// <summary>
                /// Gets the value as a <see cref="TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray" />.
                /// </summary>
                /// <param name="result">The result of the conversions.</param>
                /// <returns><see langword="true" /> if the conversion was valid.</returns>
                public bool TryGetAsJsonObjectArray(out TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray result)
                {
                    result = this.As<TestML.WorkingDraft.TestCase.ArrangeEntity.VarsEntity.JsonObjectArray>();
                    return result.IsValid();
                }
            }
        }
    }
}
